Изможеров Илья. V2.0
TrueCraftWorld/prosoftTileGame pull request #2
Opened 2024-03-22 17:10 UTC by TrueCraftWorld

Version 2.0 - Main difference - only 1 Qtimer for drop control instead of 1 for each tile.

2024-03-27 18:15 UTC, Toxin65 commented on mainwindow.cpp
> +    const int tile_size = 30;
Можно уж `constexpr` тогда.

2024-03-27 18:16 UTC, Toxin65 commented on mainwindow.cpp
> +    int butNum = 0;
Это явно лишнее.

2024-03-27 18:16 UTC, Toxin65 commented on mainwindow.cpp
> +    this->setWindowTitle(QString("SQUARE FALLDOWN"));
`this->` как правило лишнее, за редким исключением.

2024-03-27 18:17 UTC, Toxin65 commented on mainwindow.cpp
> +                     [=]() mutable {
`[=]` Так делать очень плохо. Захватывать нужно необходимый минимум. Захват всего и вся, тем более по значению, очень нехорошо.

2024-03-27 18:19 UTC, Toxin65 commented on mainwindow.cpp
> +        int speed = QRandomGenerator::global()->bounded(lowestSpeed,highestSpeed);
Я, наверное, не говорил. `const` лучше писать всегда, кроме тех случаев когда это действительно нельзя.

2024-03-27 18:20 UTC, Toxin65 commented on mainwindow.cpp
> +        dropStepMap.insert(test, speed);
Оверкомлексити... Слишком сложно. Не нужно.

2024-03-27 18:20 UTC, Toxin65 commented on mainwindow.cpp
> +        newButton->setPalette(palette1);
Это не требовалось по ТЗ. Лишние строки. Нууу, если хотите, пусть будет.

2024-03-27 18:21 UTC, Toxin65 commented on mainwindow.cpp
> +        tile_size));
Переносы по кодстайлу выглядят ужасно. Ужасно нечитаемо.

2024-03-27 18:22 UTC, Toxin65 commented on mainwindow.cpp
> +        QObject::connect(bigDropTimer, &QTimer::timeout,  newButton, [=] {
Использование единого таймера, безусловно интересный подход.

2024-03-27 18:24 UTC, Toxin65 commented on mainwindow.cpp
> +                                                        dropStepMap[newButton->accessibleName()];
Дорахо бохато. Не нужно. Просто захватывайте скорость в лямбду. Ведь и так на каждую кнопку своя лямбда. Пусть оно живёт не в `dropStepMap`, и доступ значительно быстрее.

2024-03-27 18:25 UTC, Toxin65 commented on mainwindow.cpp
> +                if (newButton->y() >= this->height() - tile_size) {
Если вы хотите заморочится, то сначала "короткую ветку". Условие инвертировать и `return`. И ниже то же.

2024-03-27 18:26 UTC, Toxin65 commented on mainwindow.cpp
> +        QObject::connect(newButton, &QPushButton::clicked, newButton, [=] { //makes it easier to play
Ну вот тут захваты просто ужас, тут только кнопка нужна.
И ещё. Тут не нужна лямбда -- напрямую сигнал в `deleteLater` направлять.

2024-03-27 18:27 UTC, Toxin65 commented on mainwindow.cpp
> +        deployTimer->setInterval(QRandomGenerator::global()->bounded(minSpawnInterval, maxSpawnInterval));
А почему это не сделать в лямбде генерации?

2024-03-27 18:28 UTC, Toxin65 requested changes
В целом нормально. Но есть серьёзные замечания.

2024-03-28 05:43 UTC, TrueCraftWorld commented on mainwindow.cpp
> +        dropStepMap.insert(test, speed);
Это про использование этого контейнера? Показалось нормальным хранить пары <имя, скорость> и map подходит под хранение пар. 
Будет ли нормально тогда спрятать скорость в какой-то параметр дефолтной QPudhButton, например, в имя?

2024-03-28 05:51 UTC, TrueCraftWorld commented on mainwindow.cpp
> +        QObject::connect(newButton, &QPushButton::clicked, newButton, [=] { //makes it easier to play
Разве должна кнопка удалятся по клику, когда уже проиграли? Лямбда только из-за этой проверки здесь.

2024-03-28 05:51 UTC, TrueCraftWorld commented on mainwindow.cpp
> +        deployTimer->setInterval(QRandomGenerator::global()->bounded(minSpawnInterval, maxSpawnInterval));
Перенёс в генерацию

2024-03-28 08:22 UTC, Toxin65 commented on mainwindow.cpp
> +        QObject::connect(newButton, &QPushButton::clicked, newButton, [=] { //makes it easier to play
Этого в ТЗ не сказано. Значит без разницы.

2024-03-28 08:24 UTC, Toxin65 commented on mainwindow.cpp
> +    auto bigDropTimer = new QTimer();
Ой ой ой. А почему у таймеров владельцы пропали??? Было правильно.

2024-03-28 08:26 UTC, Toxin65 commented on mainwindow.cpp
> +                     [this, highBorder, tile_size, bigDropTimer, deployTimer]() {
`highBorder, tile_size` лишние. Подумайте почему.
`deployTimer` зачем?

2024-03-28 08:31 UTC, Toxin65 commented on mainwindow.cpp
> +        dropStepMap.insert(test, speed);
Ниже ответил "Просто захватывайте скорость в лямбду. "

2024-03-28 08:36 UTC, Toxin65 commented on mainwindow.cpp
> +        QObject::connect(bigDropTimer, &QTimer::timeout,  newButton, [this, newButton, tile_size] {
`tile_size` лишнее.

2024-03-28 08:37 UTC, Toxin65 commented on mainwindow.cpp
> +            int step = newButton->accessibleName().toInt();
Не надо так делать, захватывайте в лямбду.

2024-03-28 08:39 UTC, Toxin65 requested changes
Появились новые замечания :(

2024-03-28 08:49 UTC, TrueCraftWorld commented on mainwindow.cpp
> +                     [this, highBorder, tile_size, bigDropTimer, deployTimer]() {
Потому что они теперь констэкпр и видны глобально. Не продумал, когда им менял объявление.

2024-03-28 09:17 UTC, TrueCraftWorld commented on mainwindow.cpp
> +            int step = newButton->accessibleName().toInt();
Т.е. для каждой кнопки своя личная лямбда с копией того значения, что захватим? 
Не осознавал, что это так работает.

2024-03-28 13:19 UTC, TrueCraftWorld commented on mainwindow.cpp
> +                     [this, highBorder, tile_size, bigDropTimer, deployTimer]() {
Про m_timer не понял. Имеется в виду вызываемый через startTimer? ,чтобы его вместе с this захватить? А как тогда ловить его сигналы - дока пишет что у него обработчик переопределяется наследником, а нам же так нельзя по ТЗ.

2024-03-28 14:11 UTC, Toxin65 commented on mainwindow.cpp
> +                     [this, highBorder, tile_size, bigDropTimer, deployTimer]() {
Верно.

2024-03-28 14:12 UTC, Toxin65 commented on mainwindow.cpp
> +            int step = newButton->accessibleName().toInt();
Она по факту для каждого своя, да. Для каждого объекта свой экземпляр. Поэтому не надо этих излишеств.

2024-04-09 09:59 UTC, Toxin65 commented on mainwindow.cpp
> +    QObject::connect(this->m_timer,
Да штош такое, питон вас покусал... Просто `m_timer`. `this` для этого не нужен.

2024-04-09 10:02 UTC, Toxin65 commented on mainwindow.cpp
> +    this->setWindowTitle(QString("SQUARE FALLDOWN"));
Не учтено, до сих пор.

2024-04-09 10:16 UTC, Toxin65 commented on mainwindow.cpp
> +                                        highBorder,
Но ведь не соответствует ТЗ же!
`- Объекты появляются в произвольном месте по всей ширине окна и в области 100 пикселей от верха окна;`

2024-04-09 10:17 UTC, TrueCraftWorld commented on mainwindow.cpp
> +    QObject::connect(this->m_timer,
Да, ускользает от взора...

Оба случая исправил

2024-04-09 10:22 UTC, Toxin65 commented on mainwindow.cpp
> +            if (newButton->underMouse()) step*=2;
Можно тернарником и сразу в конст.

2024-04-09 10:31 UTC, Toxin65 approved these changes

2024-07-15 12:43 UTC, merged